# Generated by Django 4.1.2 on 2025-01-14 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=3000)),
                ('socialMedia', models.CharField(blank=True, choices=[('FACEBOOK', 'FaceBook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('THREADS', 'Threads')], default='LINKEDIN', max_length=40, null=True)),
                ('response', models.CharField(blank=True, max_length=100000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rPapers', related_query_name='rPapers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('companyRole', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('socialsName', models.CharField(blank=True, choices=[('FACEBOOK', 'FaceBook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('THREADS', 'Threads')], max_length=40, null=True)),
                ('content', models.CharField(blank=True, max_length=100000)),
                ('posted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsToQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('used', models.BooleanField(default=False)),
                ('socialMedia', models.CharField(blank=True, choices=[('FACEBOOK', 'FaceBook'), ('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('THREADS', 'Threads')], max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', related_query_name='fields_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('energyOperationCertificate', models.URLField(max_length=30)),
                ('accNumber', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', related_query_name='comp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
