# Generated by Django 4.1.2 on 2024-05-18 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('energyOperationCertificate', models.URLField(max_length=30)),
                ('accNumber', models.CharField(max_length=100)),
                ('bankName', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('accCode', models.CharField(max_length=30)),
                ('issuerCode', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTechnicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('commissioningDate', models.DateField()),
                ('effectiveDate', models.DateField()),
                ('isGridConnected', models.BooleanField(default=False)),
                ('isFeedInTarrif', models.BooleanField(default=False)),
                ('percentageRenewable', models.BooleanField(default=False)),
                ('otherLabellingScheme', models.CharField(max_length=30)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviceLocation', to='app.device')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('companyRole', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=30)),
                ('postalCode', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('Device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviceLocation', to='app.devicetechnicalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=2000)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceDocuments', to='app.device')),
            ],
        ),
    ]
