# Generated by Django 4.1.2 on 2024-05-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetechnicalinformation',
            name='percentageRenewable',
            field=models.IntegerField(default=0),
        ),
    ]
