# Generated by Django 4.1.2 on 2024-05-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_devicetechnicalinformation_percentagerenewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetechnicalinformation',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technicalInformation', related_query_name='technicalInfo', to='app.device'),
        ),
    ]
