# Generated by Django 4.1.2 on 2024-06-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Device',
            new_name='device',
        ),
    ]
