# Generated by Django 4.1.2 on 2024-12-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_device_location_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedocuments',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicetechnicalinformation',
            name='device',
        ),
        migrations.RemoveField(
            model_name='location',
            name='device',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceDocuments',
        ),
        migrations.DeleteModel(
            name='DeviceTechnicalInformation',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
