# Generated by Django 4.1.2 on 2024-12-28 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_remove_devicedocuments_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('socialsName', models.CharField(choices=[('FaceBook', 'FACEBOOK'), ('Instagram', 'INSTAGRAM'), ('Twitter', 'TWITTER'), ('LinkedIn', 'LINKEDIN'), ('Threads', 'Threads')], max_length=20)),
                ('content', models.CharField(blank=True, max_length=100000)),
                ('posted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=30)),
                ('response', models.CharField(blank=True, max_length=100000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchPapers', related_query_name='researchPapers', to='app.posts')),
            ],
        ),
    ]
